feat: добавить сервис статистики
Kadyke/java-explore-with-me pull request #3
Opened 2023-07-21 16:04 UTC by Kadyke

2023-07-23 07:19 UTC, db-exp requested changes

2023-07-23 07:19 UTC, db-exp commented on stats-server/src/main/java/ru/practicum/controller/Controller.java
> +    public HitDto saveHit(@RequestBody HitDto hitDto) {
можно Valid

2023-07-23 07:19 UTC, db-exp commented on stats-server/src/main/java/ru/practicum/mapper/HitMapper.java
> +    public Hit mapRow(ResultSet rs, int rowNum) throws SQLException {
я бы разделил, а то получается класс маппер, который и на уровень клиента может и с бд поковыряться

2023-07-23 07:19 UTC, db-exp commented on stats-server/src/main/java/ru/practicum/mapper/HitMapper.java
> +    public Hit mapRow(ResultSet rs, int rowNum) throws SQLException {
бд маппер лучше отправить в слой БД как StatMapper

2023-07-23 07:19 UTC, db-exp commented on stats-server/src/main/java/ru/practicum/service/StatsService.java
> +                stats.addAll(repository.getStatsWithUniqueIp(end, start, uri));
не стоит запрашивать по одному - очень неоптимально, лучше сделать запрос, который вернет все сразу

2023-07-23 07:29 UTC, Kadyke commented on pom.xml
> +	<dependencies>
+

2023-07-23 07:46 UTC, Kadyke commented on stats-client/src/main/java/ru/practicum/HitDto.java
> +    @NotNull
++

2023-07-23 07:46 UTC, Kadyke commented on stats-client/src/main/java/ru/practicum/HitDto.java
> +    @NotNull
++

2023-07-23 07:47 UTC, Kadyke commented on stats-client/src/main/java/ru/practicum/HitDto.java
> +    @NotNull
++

2023-07-23 07:47 UTC, Kadyke commented on stats-server/src/main/java/ru/practicum/controller/Controller.java
> +    public HitDto saveHit(@RequestBody HitDto hitDto) {
А зачем valid, если вся валидация в клиенте?

2023-07-23 09:18 UTC, Kadyke commented on stats-server/pom.xml
> +    <parent>
я так уже пробовал делать, докер просто во время компиляции проекта висит и все, сейчас еще раз 2 попробовал, 1 раз просто перемещал модули, потом пересоздавал, все равно висит и все, все образы перед этим очищал, перепаковку мавена делал

2023-07-23 13:28 UTC, Kadyke commented on stats-client/src/main/java/ru/practicum/Client.java
> +        RestTemplateBuilder builder = new RestTemplateBuilder();
++

2023-07-23 13:30 UTC, Kadyke commented on stats-server/src/main/java/ru/practicum/controller/Controller.java
> +    public HitDto saveHit(@RequestBody HitDto hitDto) {
++

2023-07-23 13:31 UTC, Kadyke commented on stats-server/src/main/java/ru/practicum/mapper/HitMapper.java
> +    public Hit mapRow(ResultSet rs, int rowNum) throws SQLException {
++

2023-07-23 14:45 UTC, Kadyke commented on stats-server/src/main/java/ru/practicum/service/StatsService.java
> +                stats.addAll(repository.getStatsWithUniqueIp(end, start, uri));
++

2023-07-23 16:11 UTC, Kadyke commented on stats-server/pom.xml
> +    <parent>
++

2023-07-24 11:22 UTC, db-exp commented on stats/stats-server/src/main/java/ru/practicum/service/StatsService.java
> +@org.springframework.stereotype.Service
org.springframework.stereotype.Service - немного режет глаза, сократи, пожалуйста, в следующем PR

2023-07-24 11:33 UTC, db-exp requested changes

2023-07-24 11:33 UTC, db-exp commented on stats/stats-client/src/main/java/ru/practicum/yandex/HitDto.java
> +public class HitDto {
по заданию нужно было вынести в отдельный модуль

2023-07-24 11:33 UTC, db-exp commented on stats/stats-client/src/main/java/ru/practicum/yandex/Stat.java
> +public class Stat {
по заданию нужно было вынести в отдельный модуль

2023-07-24 11:33 UTC, db-exp commented on stats/stats-server/src/main/java/ru/practicum/repository/Repository.java
> +public class Repository {
очень неудачное название - пересекается с аннотацией

2023-07-24 11:33 UTC, db-exp commented on stats/stats-server/pom.xml
> +            <artifactId>stats-client</artifactId>
так как нет модуля общих dto сюда затягивается клиент, а это не очень хорошо с точки зрения связности

2023-07-24 11:33 UTC, db-exp commented on pom.xml
> +	<dependencies>
все еще вижу <dependencies> , если это не кеш гитхаба, то просьба убрать

2023-07-24 13:46 UTC, Kadyke commented on stats/stats-server/src/main/java/ru/practicum/service/StatsService.java
> +@org.springframework.stereotype.Service
++

2023-07-24 13:46 UTC, Kadyke commented on stats/stats-client/src/main/java/ru/practicum/yandex/HitDto.java
> +public class HitDto {
Наставник сказал, что это по желанию

2023-07-24 13:46 UTC, Kadyke commented on stats/stats-client/src/main/java/ru/practicum/yandex/Stat.java
> +public class Stat {
Наставник сказал, что это по желанию

2023-07-24 13:48 UTC, Kadyke commented on stats/stats-server/src/main/java/ru/practicum/repository/Repository.java
> +public class Repository {
++

2023-07-24 13:51 UTC, Kadyke commented on pom.xml
> +	<dependencies>
много раз переделал мавен, судя по всему в последний раз, забыл убрать, сейчас убрал

2023-07-24 14:01 UTC, Kadyke commented on stats/stats-server/pom.xml
> +            <artifactId>stats-client</artifactId>
Наставник сказал, что это по желанию

2023-07-24 21:33 UTC, db-exp approved these changes

2023-07-26 15:27 UTC, merged