feat: добавить основной сервис
Kadyke/java-explore-with-me pull request #4
Opened 2023-08-03 04:37 UTC by Kadyke

2023-08-04 21:49 UTC, db-exp requested changes

2023-08-04 21:49 UTC, db-exp commented on stats/stats-client/src/main/java/ru/practicum/yandex/Client.java
> +        RestTemplateBuilder builder = new RestTemplateBuilder();
тут лучше как бин получать

2023-08-04 21:49 UTC, db-exp commented on ewm-service/src/main/java/ru/practicum/service/UserService.java
> +public class UserService {
предлагаю добавить Transactional ( c readOnly там, где только чтение)

2023-08-04 21:49 UTC, db-exp commented on ewm-service/src/main/java/ru/practicum/service/RequestService.java
> +public class RequestService {
предлагаю добавить Transactional ( c readOnly там, где только чтение)

2023-08-04 21:49 UTC, db-exp commented on ewm-service/src/main/java/ru/practicum/service/CompilationService.java
> +public class CompilationService {
предлагаю добавить Transactional ( c readOnly там, где только чтение)

2023-08-04 21:49 UTC, db-exp commented on ewm-service/src/main/java/ru/practicum/repository/UserRepository.java
> +@Transactional
а вот отсюда transactional можно убрать - лучше его делать на сервисах - там, где идут несколько действий  - например, создали сначала одно, потом указали id для создания другого Я в пути!

2023-08-04 21:49 UTC, db-exp commented on ewm-service/src/main/java/ru/practicum/repository/RequestRepository.java
> +public interface RequestRepository extends JpaRepository<Request, Long> {
тут тоже предлагаю аннотацию использовать на сервисе

2023-08-04 21:49 UTC, db-exp commented on ewm-service/src/main/java/ru/practicum/service/CategoryService.java
> +public class CategoryService {
как и в других сервисах - лучше убрать Transactional с репозитория и использовать на классе с указанием чтение или чтение/запись

2023-08-04 21:49 UTC, db-exp commented on ewm-service/src/main/java/ru/practicum/service/EventService.java
> +public class EventService {
как и в других сервисах - лучше убрать Transactional с репозитория и использовать на классе с указанием чтение или чтение/запись

2023-08-04 21:49 UTC, db-exp commented on ewm-service/src/main/java/ru/practicum/repository/CategoryRepository.java
> +@Transactional
лучше поменять местами с сервисом

2023-08-04 21:49 UTC, db-exp commented on ewm-service/src/main/java/ru/practicum/ConfigurationBeans.java
> +    public Client client(@Value("${service.url}") String serviceUrl) {
как мне кажется, лучше поставить аннотацию Service на Client и уже там ожидать в конструкторе Value("${service.url}")

2023-08-04 21:49 UTC, db-exp commented on ewm-service/src/main/java/ru/practicum/repository/CompilationRepository.java
> +@Transactional
предлагаю аннотацию переместить в сервис и учесть readOnly=true

2023-08-05 05:59 UTC, Kadyke commented on stats/stats-client/src/main/java/ru/practicum/yandex/Client.java
> +        RestTemplateBuilder builder = new RestTemplateBuilder();
++

2023-08-05 06:12 UTC, Kadyke commented on ewm-service/src/main/java/ru/practicum/ConfigurationBeans.java
> +    public Client client(@Value("${service.url}") String serviceUrl) {
я не понимаю, мне url нужен для создания RestTemplate, который нужно создавать в бине, я тогда его создаю в конфигарциях в мэйне при создания Client, и здесь же должен передать url, без урл бин просто не создается

2023-08-05 06:12 UTC, Kadyke commented on ewm-service/src/main/java/ru/practicum/service/UserService.java
> +public class UserService {
++

2023-08-05 06:22 UTC, Kadyke commented on ewm-service/src/main/java/ru/practicum/service/RequestService.java
> +public class RequestService {
++

2023-08-05 06:22 UTC, Kadyke commented on ewm-service/src/main/java/ru/practicum/service/CompilationService.java
> +public class CompilationService {
++

2023-08-05 06:22 UTC, Kadyke commented on ewm-service/src/main/java/ru/practicum/repository/UserRepository.java
> +@Transactional
++

2023-08-05 06:22 UTC, Kadyke commented on ewm-service/src/main/java/ru/practicum/repository/RequestRepository.java
> +public interface RequestRepository extends JpaRepository<Request, Long> {
++

2023-08-05 06:22 UTC, Kadyke commented on ewm-service/src/main/java/ru/practicum/service/CategoryService.java
> +public class CategoryService {
++

2023-08-05 06:22 UTC, Kadyke commented on ewm-service/src/main/java/ru/practicum/service/EventService.java
> +public class EventService {
++

2023-08-05 06:22 UTC, Kadyke commented on ewm-service/src/main/java/ru/practicum/repository/CategoryRepository.java
> +@Transactional
++

2023-08-05 06:23 UTC, Kadyke commented on ewm-service/src/main/java/ru/practicum/repository/CompilationRepository.java
> +@Transactional
++

2023-08-05 11:47 UTC, db-exp commented on ewm-service/src/main/java/ru/practicum/ConfigurationBeans.java
> +    public Client client(@Value("${service.url}") String serviceUrl) {
Я имею ввиду, что создавать бин можно прямо в виде сервиса без new в отдельном файле конфигурации.
Если хочешь и можешь - переделай, пожалуйста, либо оставляй как есть

2023-08-05 11:58 UTC, db-exp approved these changes

2023-08-05 13:29 UTC, merged