feat: добавить лайки
Kadyke/java-explore-with-me pull request #5
Opened 2023-08-06 10:14 UTC by Kadyke

Не до конца понял по поводу RequestService и EventService, ссылкой на чужие репозитории там нет, только на сервисы друг друга

2023-08-07 13:04 UTC, db-exp commented
https://github.com/Kadyke/java-explore-with-me/pull/5#issue-1838143875
Если я правильно помню я просил Transitional раскидать с репозиториев на сервисы

2023-08-07 13:04 UTC, db-exp requested changes

2023-08-07 15:28 UTC, Kadyke commented on README.md
> +https://github.com/Kadyke/java-explore-with-me/pull/5
++, Transitional тоже ++

2023-08-08 11:39 UTC, db-exp approved these changes

2023-08-24 14:17 UTC, merged